import type { PortalState, Role, UserProfile } from "./types";

export const demoProfiles: Record<Role, UserProfile> = {
  student: {
    uid: "demo-student",
    name: "Sofía Martínez",
    email: "sofia@cehf.edu.mx",
    role: "student",
    grade: "5.º",
    group: "A",
    initials: "SM",
  },
  teacher: {
    uid: "demo-teacher",
    name: "Mariana López",
    email: "mariana.lopez@cehf.edu.mx",
    role: "teacher",
    subjects: ["Español", "Ciencias"],
    group: "5.º A",
    initials: "ML",
  },
  director: {
    uid: "demo-director",
    name: "Alejandra Torres",
    email: "direccion.primaria@cehf.edu.mx",
    role: "director",
    subjects: [],
    initials: "AT",
  },
};

export const createDemoState = (): PortalState => ({
  week: {
    id: "week-07",
    label: "Semana 7",
    range: "20–24 de julio",
    status: "active",
    title: "Exploramos cómo cambia nuestro entorno",
    welcomeMessage:
      "Esta semana observaremos, leeremos y explicaremos los cambios que ocurren a nuestro alrededor.",
    objectives: [
      "Identificar cambios físicos y químicos con ejemplos cotidianos.",
      "Explicar una idea principal usando evidencias de una lectura.",
      "Resolver problemas con fracciones equivalentes.",
    ],
    completion: 68,
  },
  reviews: [
    {
      id: "review-ciencias",
      title: "Cambios de la materia",
      subject: "Ciencias",
      purpose: "Practicar",
      duration: 8,
      questions: 6,
      progress: 50,
      attempts: 2,
      status: "published",
    },
    {
      id: "review-mates",
      title: "Fracciones equivalentes",
      subject: "Matemáticas",
      purpose: "Reforzar",
      duration: 10,
      questions: 8,
      progress: 100,
      attempts: 2,
      status: "completed",
    },
    {
      id: "review-lectura",
      title: "Ideas que explican",
      subject: "Español",
      purpose: "Recordar",
      duration: 6,
      questions: 4,
      progress: 0,
      attempts: 1,
      status: "published",
    },
  ],
  tasks: [
    {
      id: "task-bitacora",
      title: "Bitácora de un cambio",
      subject: "Ciencias",
      description:
        "Observa un cambio en casa, descríbelo y explica qué evidencia encontraste.",
      dueLabel: "Mañana, 20:00",
      dueAt: "2026-07-24T02:00:00.000Z",
      status: "published",
      type: "Entrega",
      objective: "Identificar cambios físicos y químicos.",
    },
    {
      id: "task-lectura",
      title: "Lectura: El jardín de Ana",
      subject: "Español",
      description:
        "Lee el cuento y escribe la idea principal en tres oraciones.",
      dueLabel: "Viernes, 18:00",
      dueAt: "2026-07-25T00:00:00.000Z",
      status: "submitted",
      type: "Lectura",
      objective: "Explicar una idea principal con evidencias.",
    },
    {
      id: "task-fracciones",
      title: "Reto de fracciones",
      subject: "Matemáticas",
      description:
        "Resuelve los seis retos y muestra dos formas de representar cada fracción.",
      dueLabel: "Viernes, 20:00",
      dueAt: "2026-07-25T02:00:00.000Z",
      status: "under_review",
      type: "Actividad",
      objective: "Resolver problemas con fracciones equivalentes.",
    },
  ],
  materials: [
    {
      id: "material-guia",
      title: "Guía visual: la materia cambia",
      subject: "Ciencias",
      description: "Una ficha breve con ejemplos para observar en casa.",
      type: "PDF",
      day: "Lunes",
      required: true,
      reviewed: true,
    },
    {
      id: "material-video",
      title: "Fracciones en la cocina",
      subject: "Matemáticas",
      description: "Video de 4 minutos con representaciones sencillas.",
      type: "Video",
      day: "Miércoles",
      required: true,
      reviewed: false,
    },
    {
      id: "material-audio",
      title: "El jardín de Ana",
      subject: "Español",
      description: "Lectura en audio con transcripción completa.",
      type: "Audio",
      day: "Jueves",
      required: false,
      reviewed: false,
    },
    {
      id: "material-ficha",
      title: "Tarjetas para recortar",
      subject: "Matemáticas",
      description: "Material imprimible para formar pares equivalentes.",
      type: "Ficha",
      day: "Jueves",
      required: false,
      reviewed: false,
    },
  ],
  progress: [
    {
      id: "progress-review",
      label: "Repaso semanal",
      detail: "Completaste 1 de 3 repasos.",
      weight: 30,
      level: "in_progress",
    },
    {
      id: "progress-tasks",
      label: "Tareas y evidencias",
      detail: "Dos evidencias entregadas; una está pendiente.",
      weight: 35,
      level: "in_progress",
    },
    {
      id: "progress-understanding",
      label: "Comprensión de objetivos",
      detail: "Explicas tus ideas con ejemplos claros.",
      weight: 25,
      level: "achieved",
    },
    {
      id: "progress-participation",
      label: "Participación",
      detail: "Compartiste una observación en el foro.",
      weight: 10,
      level: "achieved",
    },
  ],
  reports: [
    {
      id: "report-week-06",
      week: "Semana 6 · 13–17 de julio",
      status: "published",
      summary:
        "Sofía participó con constancia y pudo explicar los pasos de sus procedimientos.",
      achievement:
        "Relacionó fracciones con situaciones cotidianas y justificó sus respuestas.",
      support:
        "Conviene releer las consignas antes de comenzar una actividad larga.",
      nextStep: "Subrayar datos importantes y escribir un plan breve.",
      teacher: "Mariana López",
      publishedAt: "17 jul, 13:20",
      version: 1,
    },
    {
      id: "report-week-07",
      week: "Semana 7 · 20–24 de julio",
      status: "draft",
      summary: "Borrador preparado con las evidencias disponibles.",
      achievement: "Identifica ejemplos de cambios físicos.",
      support: "Falta completar el repaso de comprensión lectora.",
      nextStep: "Terminar los pendientes y revisar la retroalimentación.",
      teacher: "Mariana López",
      version: 1,
    },
  ],
  wallPosts: [
    {
      id: "wall-garden",
      title: "Nuestro jardín también cuenta historias",
      excerpt:
        "El grupo de 5.º observó polinizadores y preparó una guía para cuidarlos.",
      category: "Medio ambiente",
      author: "5.º A",
      group: "5.º A",
      publishedAt: "22 jul",
      accent: "mint",
      status: "published",
      favorite: false,
    },
    {
      id: "wall-reading",
      title: "Tres libros para viajar sin salir del salón",
      excerpt:
        "Recomendaciones breves preparadas por el club de lectura de primaria.",
      category: "Lecturas",
      author: "Club de lectura",
      group: "4.º–6.º",
      publishedAt: "21 jul",
      accent: "violet",
      status: "published",
      favorite: true,
    },
    {
      id: "wall-science",
      title: "¿Por qué cambia de color una manzana?",
      excerpt:
        "Una explicación sencilla del experimento que hicimos esta semana.",
      category: "Ciencia y curiosidades",
      author: "Mariana López",
      group: "5.º A",
      publishedAt: "20 jul",
      accent: "coral",
      status: "published",
      favorite: false,
    },
  ],
  forumTopics: [
    {
      id: "forum-question",
      title: "Pregunta de la semana",
      prompt:
        "¿Qué cambio has observado en tu entorno y qué evidencia te ayuda a explicarlo?",
      subject: "Ciencias",
      group: "5.º A",
      closesAt: "Cierra el viernes",
      status: "open",
      replies: [
        {
          id: "reply-teacher",
          author: "Mariana López",
          initials: "ML",
          body: "Recuerda describir primero lo que observaste y después explicar por qué cambió.",
          createdAt: "Hoy, 08:15",
          teacher: true,
        },
        {
          id: "reply-student",
          author: "Diego R.",
          initials: "DR",
          body: "El hielo se convirtió en agua. Lo supe porque cambió su forma pero seguía siendo agua.",
          createdAt: "Hoy, 09:02",
        },
      ],
    },
    {
      id: "forum-reading",
      title: "Club de lectura: El jardín de Ana",
      prompt: "¿Qué decisión del personaje cambió el final de la historia?",
      subject: "Español",
      group: "5.º A",
      closesAt: "Cierra el lunes",
      status: "open",
      replies: [],
    },
  ],
  notifications: [
    {
      id: "notif-task",
      title: "Tienes una tarea para mañana",
      detail: "Bitácora de un cambio · Ciencias",
      category: "task",
      createdAt: "Hace 12 min",
      read: false,
    },
    {
      id: "notif-material",
      title: "Nuevo material de Matemáticas",
      detail: "Fracciones en la cocina",
      category: "material",
      createdAt: "Ayer",
      read: false,
    },
    {
      id: "notif-report",
      title: "Tu reporte de la Semana 6 está listo",
      detail: "Puedes revisarlo con tu familia.",
      category: "report",
      createdAt: "17 jul",
      read: true,
    },
  ],
  settings: {
    theme: "light",
    reducedMotion: false,
    whatsappEnabled: true,
    quietHours: "20:00–07:00",
  },
});

export const subjectColors: Record<string, string> = {
  Ciencias: "mint",
  Matemáticas: "gold",
  Español: "coral",
  Comunidad: "violet",
};

export const roleLabel: Record<Role, string> = {
  student: "Estudiante",
  teacher: "Docente",
  director: "Dirección",
};
