import type { PortalState, Role, UserProfile } from "./types";

export const demoProfiles: Record<Role, UserProfile> = {
  student: {
    uid: "demo-student",
    name: "Sofía Martínez",
    email: "sofia@cehf.edu.mx",
    role: "student",
    grade: "5.º",
    group: "A",
    initials: "SM",
  },
  teacher: {
    uid: "demo-teacher",
    name: "Mariana López",
    email: "mariana.lopez@cehf.edu.mx",
    role: "teacher",
    subjects: ["Español", "Ciencias"],
    group: "5.º A",
    initials: "ML",
  },
  director: {
    uid: "demo-director",
    name: "Alejandra Torres",
    email: "direccion.primaria@cehf.edu.mx",
    role: "director",
    subjects: [],
    initials: "AT",
  },
};

export const createDemoState = (): PortalState => ({
  week: {
    id: "week-07",
    label: "Semana 7",
    range: "20–24 de julio",
    status: "active",
    title: "Exploramos cómo cambia nuestro entorno",
    welcomeMessage:
      "Esta semana observaremos, leeremos y explicaremos los cambios que ocurren a nuestro alrededor.",
    objectives: [
      "Identificar cambios físicos y químicos con ejemplos cotidianos.",
      "Explicar una idea principal usando evidencias de una lectura.",
      "Resolver problemas con fracciones equivalentes.",
    ],
    completion: 68,
  },
  weeklyVerse: {
    text: "Todo lo puedo en Cristo que me fortalece.",
    reference: "Filipenses 4:13",
    updatedBy: "Dirección",
    updatedAt: "2026-07-20T13:00:00.000Z",
  },
  reviews: [
    {
      id: "review-ciencias",
      title: "Cambios de la materia",
      subject: "Ciencias",
      purpose: "Practicar",
      duration: 8,
      questions: 6,
      progress: 50,
      attempts: 2,
      status: "published",
    },
    {
      id: "review-mates",
      title: "Fracciones equivalentes",
      subject: "Matemáticas",
      purpose: "Reforzar",
      duration: 10,
      questions: 8,
      progress: 100,
      attempts: 2,
      status: "completed",
    },
    {
      id: "review-lectura",
      title: "Ideas que explican",
      subject: "Español",
      purpose: "Recordar",
      duration: 6,
      questions: 4,
      progress: 0,
      attempts: 1,
      status: "published",
    },
  ],
  tasks: [
    {
      id: "task-bitacora",
      title: "Bitácora de un cambio",
      subject: "Ciencias",
      description:
        "Observa un cambio en casa, descríbelo y explica qué evidencia encontraste.",
      dueLabel: "Mañana, 20:00",
      dueAt: "2026-07-24T02:00:00.000Z",
      status: "published",
      type: "Entrega",
      objective: "Identificar cambios físicos y químicos.",
    },
    {
      id: "task-lectura",
      title: "Lectura: El jardín de Ana",
      subject: "Español",
      description:
        "Lee el cuento y escribe la idea principal en tres oraciones.",
      dueLabel: "Viernes, 18:00",
      dueAt: "2026-07-25T00:00:00.000Z",
      status: "submitted",
      type: "Lectura",
      objective: "Explicar una idea principal con evidencias.",
    },
    {
      id: "task-fracciones",
      title: "Reto de fracciones",
      subject: "Matemáticas",
      description:
        "Resuelve los seis retos y muestra dos formas de representar cada fracción.",
      dueLabel: "Viernes, 20:00",
      dueAt: "2026-07-25T02:00:00.000Z",
      status: "under_review",
      type: "Actividad",
      objective: "Resolver problemas con fracciones equivalentes.",
    },
  ],
  materials: [
    {
      id: "material-guia",
      title: "Guía visual: la materia cambia",
      subject: "Ciencias",
      description: "Una ficha breve con ejemplos para observar en casa.",
      type: "PDF",
      day: "Lunes",
      required: true,
      reviewed: true,
    },
    {
      id: "material-video",
      title: "Fracciones en la cocina",
      subject: "Matemáticas",
      description: "Video de 4 minutos con representaciones sencillas.",
      type: "Video",
      day: "Miércoles",
      required: true,
      reviewed: false,
    },
    {
      id: "material-audio",
      title: "El jardín de Ana",
      subject: "Español",
      description: "Lectura en audio con transcripción completa.",
      type: "Audio",
      day: "Jueves",
      required: false,
      reviewed: false,
    },
    {
      id: "material-ficha",
      title: "Tarjetas para recortar",
      subject: "Matemáticas",
      description: "Material imprimible para formar pares equivalentes.",
      type: "Ficha",
      day: "Jueves",
      required: false,
      reviewed: false,
    },
  ],
  progress: [
    {
      id: "progress-review",
      label: "Repaso semanal",
      detail: "Completaste 1 de 3 repasos.",
      weight: 30,
      level: "in_progress",
    },
    {
      id: "progress-tasks",
      label: "Tareas y evidencias",
      detail: "Dos evidencias entregadas; una está pendiente.",
      weight: 35,
      level: "in_progress",
    },
    {
      id: "progress-understanding",
      label: "Comprensión de objetivos",
      detail: "Explicas tus ideas con ejemplos claros.",
      weight: 25,
      level: "achieved",
    },
    {
      id: "progress-participation",
      label: "Participación",
      detail: "Compartiste una observación en el foro.",
      weight: 10,
      level: "achieved",
    },
  ],
  reports: [
    {
      id: "report-week-06",
      week: "Semana 6 · 13–17 de julio",
      status: "published",
      summary:
        "Sofía participó con constancia y pudo explicar los pasos de sus procedimientos.",
      achievement:
        "Relacionó fracciones con situaciones cotidianas y justificó sus respuestas.",
      support:
        "Conviene releer las consignas antes de comenzar una actividad larga.",
      nextStep: "Subrayar datos importantes y escribir un plan breve.",
      teacher: "Mariana López",
      publishedAt: "17 jul, 13:20",
      version: 1,
    },
    {
      id: "report-week-07",
      week: "Semana 7 · 20–24 de julio",
      status: "draft",
      summary: "Borrador preparado con las evidencias disponibles.",
      achievement: "Identifica ejemplos de cambios físicos.",
      support: "Falta completar el repaso de comprensión lectora.",
      nextStep: "Terminar los pendientes y revisar la retroalimentación.",
      teacher: "Mariana López",
      version: 1,
    },
  ],
  wallPosts: [
    {
      id: "wall-garden",
      title: "Nuestro jardín también cuenta historias",
      excerpt:
        "El grupo de 5.º observó polinizadores y preparó una guía para cuidarlos.",
      category: "Medio ambiente",
      author: "5.º A",
      group: "5.º A",
      publishedAt: "22 jul",
      accent: "mint",
      status: "published",
      favorite: false,
    },
    {
      id: "wall-reading",
      title: "Tres libros para viajar sin salir del salón",
      excerpt:
        "Recomendaciones breves preparadas por el club de lectura de primaria.",
      category: "Lecturas",
      author: "Club de lectura",
      group: "4.º–6.º",
      publishedAt: "21 jul",
      accent: "violet",
      status: "published",
      favorite: true,
    },
    {
      id: "wall-science",
      title: "¿Por qué cambia de color una manzana?",
      excerpt:
        "Una explicación sencilla del experimento que hicimos esta semana.",
      category: "Ciencia y curiosidades",
      author: "Mariana López",
      group: "5.º A",
      publishedAt: "20 jul",
      accent: "coral",
      status: "published",
      favorite: false,
    },
  ],
  forumTopics: [
    {
      id: "topic-cambios",
      forumId: "science-5a",
      forumName: "Ciencias · 5.º A",
      title: "Pregunta de la semana",
      prompt:
        "¿Qué cambio has observado en tu entorno y qué evidencia te ayuda a explicarlo?",
      kind: "weekly_question",
      subject: "Ciencias",
      group: "5.º A",
      responsible: "Mariana López",
      participants: ["Mariana", "Sofía", "Diego", "Emilia", "Mateo"],
      opensAt: "Lun, 20 jul · 07:00",
      closesAt: "Cierra el viernes",
      status: "open",
      allowReplies: true,
      allowAttachments: true,
      pinned: true,
      unreadCount: 2,
      lastActivity: "Hace 8 min",
      replies: [
        {
          id: "reply-teacher",
          author: "Mariana López",
          initials: "ML",
          body: "Recuerda describir primero lo que observaste y después explicar por qué cambió.",
          createdAt: "Hoy, 08:15",
          teacher: true,
          reactions: { helpful: 6 },
          markedAnswer: true,
        },
        {
          id: "reply-student",
          author: "Diego R.",
          initials: "DR",
          body: "El hielo se convirtió en agua. Lo supe porque cambió su forma pero seguía siendo agua.",
          createdAt: "Hoy, 09:02",
          reactions: { helpful: 4, interesting: 2 },
          attachment: {
            id: "attachment-ice",
            name: "mi-observacion-del-hielo.jpg",
            type: "image",
            sizeLabel: "Imagen · 1.2 MB",
          },
        },
        {
          id: "reply-sofia",
          parentId: "reply-student",
          author: "Sofía Martínez",
          initials: "SM",
          body: "También noté que volvió a congelarse cuando lo pusimos otra vez en el congelador.",
          createdAt: "Hoy, 09:16",
          reactions: { celebrate: 1 },
        },
      ],
    },
    {
      id: "topic-reading",
      forumId: "reading-club",
      forumName: "Club de lectura",
      title: "El jardín de Ana: decisiones que cambian historias",
      prompt: "¿Qué decisión del personaje cambió el final de la historia?",
      kind: "reading_club",
      subject: "Español",
      group: "5.º A",
      responsible: "Mariana López",
      participants: ["Mariana", "Sofía", "Diego", "Emilia"],
      opensAt: "Mié, 22 jul · 10:00",
      closesAt: "Cierra el lunes",
      status: "open",
      allowReplies: true,
      allowAttachments: false,
      unreadCount: 1,
      lastActivity: "Hace 32 min",
      replies: [
        {
          id: "reply-emilia-reading",
          author: "Emilia G.",
          initials: "EG",
          body: "Ana decidió escuchar a su abuelo y cuidar el jardín en vez de arrancar las plantas. Eso permitió que regresaran las mariposas.",
          createdAt: "Hoy, 10:20",
          reactions: { helpful: 3, celebrate: 2 },
        },
      ],
    },
    {
      id: "topic-fractions-help",
      forumId: "math-5a",
      forumName: "Matemáticas · 5.º A",
      title: "Dudas del reto de fracciones",
      prompt:
        "Comparte en qué paso te atoraste. Explica lo que ya intentaste para que podamos ayudarte.",
      kind: "task_help",
      subject: "Matemáticas",
      group: "5.º A",
      responsible: "Jorge Salgado",
      participants: ["Jorge", "Sofía", "Diego", "Mateo", "Lucía"],
      opensAt: "Mar, 21 jul · 12:00",
      closesAt: "Cierra mañana, 20:00",
      status: "open",
      allowReplies: true,
      allowAttachments: true,
      lastActivity: "Hace 1 h",
      replies: [
        {
          id: "reply-mateo-fractions",
          author: "Mateo V.",
          initials: "MV",
          body: "No entiendo por qué 2/4 y 1/2 ocupan el mismo espacio si tienen números diferentes.",
          createdAt: "Ayer, 18:42",
          reactions: { interesting: 3 },
        },
        {
          id: "reply-teacher-fractions",
          parentId: "reply-mateo-fractions",
          author: "Jorge Salgado",
          initials: "JS",
          body: "Piensa en dos pizzas del mismo tamaño: una cortada en dos y otra en cuatro. ¿Cuántas piezas necesitas de cada una para cubrir lo mismo?",
          createdAt: "Ayer, 19:04",
          teacher: true,
          markedAnswer: true,
          reactions: { helpful: 7 },
        },
      ],
    },
    {
      id: "topic-playground",
      forumId: "community-5a",
      forumName: "Nuestro grupo · 5.º A",
      title: "Una idea para mejorar nuestro recreo",
      prompt:
        "Propón una idea que ayude a que todas y todos podamos jugar y convivir mejor.",
      kind: "group_chat",
      subject: "Comunidad",
      group: "5.º A",
      responsible: "Mariana López",
      participants: ["Mariana", "Sofía", "Diego", "Emilia", "Mateo"],
      opensAt: "Lun, 20 jul · 08:00",
      closesAt: "Cierra el viernes",
      status: "open",
      allowReplies: true,
      allowAttachments: false,
      unreadCount: 3,
      lastActivity: "Hace 2 h",
      replies: [
        {
          id: "reply-lucia-playground",
          author: "Lucía P.",
          initials: "LP",
          body: "Podemos prestar juegos de mesa y hacer una lista para turnarnos.",
          createdAt: "Hoy, 08:32",
          reactions: { celebrate: 5, helpful: 2 },
        },
        {
          id: "reply-reportado",
          author: "Diego R.",
          initials: "DR",
          body: "No me parece buena idea porque algunos nunca cuidan nada.",
          createdAt: "Hoy, 08:47",
          reports: 1,
          reactions: { interesting: 1 },
        },
      ],
    },
    {
      id: "topic-wall-pollinators",
      forumId: "wall-community",
      forumName: "Periódico mural",
      title: "Después de leer: cuidemos a los polinizadores",
      prompt:
        "Elige una acción de la guía del periódico y cuéntanos cómo podríamos realizarla en la escuela.",
      kind: "wall",
      subject: "Ciencias",
      group: "4.º–6.º",
      responsible: "Comité editorial",
      participants: ["Mariana", "Jorge", "Sofía", "Emilia"],
      opensAt: "Lun, 20 jul · 13:00",
      closesAt: "Tema cerrado",
      status: "closed",
      allowReplies: true,
      allowAttachments: false,
      lastActivity: "Ayer",
      replies: [
        {
          id: "reply-wall-pollinators",
          author: "Sofía Martínez",
          initials: "SM",
          body: "Podríamos dejar un espacio con flores nativas y poner un letrero para no pisarlas.",
          createdAt: "Ayer, 13:22",
          reactions: { celebrate: 8, helpful: 4 },
        },
      ],
    },
    {
      id: "topic-experiment-preview",
      forumId: "science-5a",
      forumName: "Ciencias · 5.º A",
      title: "Antes del experimento: ¿qué crees que ocurrirá?",
      prompt:
        "Publica una predicción breve antes de comenzar el experimento del lunes.",
      kind: "subject",
      subject: "Ciencias",
      group: "5.º A",
      responsible: "Mariana López",
      participants: ["Mariana", "Sofía", "Diego", "Emilia", "Mateo"],
      opensAt: "Se abre el lunes · 07:00",
      closesAt: "Cierra el lunes · 12:00",
      status: "scheduled",
      allowReplies: true,
      allowAttachments: false,
      lastActivity: "Programado",
      replies: [],
    },
    {
      id: "topic-institutional-notice",
      forumId: "institutional",
      forumName: "Avisos CEHF",
      title: "Feria de aprendizajes: información para la comunidad",
      prompt:
        "La feria se realizará el viernes a las 12:30. Cada grupo presentará una experiencia de su semana.",
      kind: "announcement",
      subject: "Comunidad",
      group: "Toda Primaria",
      responsible: "Dirección Primaria",
      participants: ["Dirección", "Docentes", "Estudiantes"],
      opensAt: "Publicado el 22 jul",
      closesAt: "Solo lectura",
      status: "open",
      allowReplies: false,
      allowAttachments: true,
      pinned: true,
      lastActivity: "Ayer",
      replies: [],
    },
  ],
  forumModeration: [
    {
      id: "case-playground-language",
      topicId: "topic-playground",
      replyId: "reply-reportado",
      author: "Diego R.",
      excerpt: "No me parece buena idea porque algunos nunca cuidan nada.",
      reason: "Lenguaje poco respetuoso",
      reportedAt: "Hace 1 h",
      status: "open",
    },
  ],
  notifications: [
    {
      id: "notif-task",
      title: "Tienes una tarea para mañana",
      detail: "Bitácora de un cambio · Ciencias",
      category: "task",
      createdAt: "Hace 12 min",
      read: false,
    },
    {
      id: "notif-material",
      title: "Nuevo material de Matemáticas",
      detail: "Fracciones en la cocina",
      category: "material",
      createdAt: "Ayer",
      read: false,
    },
    {
      id: "notif-report",
      title: "Tu reporte de la Semana 6 está listo",
      detail: "Puedes revisarlo con tu familia.",
      category: "report",
      createdAt: "17 jul",
      read: true,
    },
  ],
  settings: {
    theme: "light",
    reducedMotion: false,
    whatsappEnabled: true,
    quietHours: "20:00–07:00",
  },
});

export const subjectColors: Record<string, string> = {
  Ciencias: "mint",
  Matemáticas: "gold",
  Español: "coral",
  Comunidad: "violet",
};

export const roleLabel: Record<Role, string> = {
  student: "Estudiante",
  teacher: "Docente",
  director: "Dirección",
};
